Fixed typos
KyloIO/kylo-docs pull request #1
Opened 2017-02-15 12:08 UTC by dscheffy

2017-02-15 17:42 UTC, freastro requested changes
Awesome, thanks! Just a couple comments:

2017-02-15 17:42 UTC, freastro commented on security/Authentication.rst
> +configuration `application.properties` file.  By default, whenever any of these profiles
This should be 'files' because there is more than one (both kylo-ui and kylo-services).

2017-02-15 17:42 UTC, freastro commented on security/Authentication.rst
> +| authenticationService.username | Yes      | ``dladmin``    | The username of the administrator |
Well this is embarrassing. Thanks for catching this! Could you fix the extra spacing so bars | line up?

2017-02-16 16:46 UTC, dscheffy commented
I hope you don't mind, but I squashed all of my changes into one commit -- it will look cleaner in the history, but it does make some of your previous comments harder to follow. I changed "file" back to "files" like you asked (I'm going to follow up with a separate question about why we need to make the same changes to both service configurations, but that's a separate issue).  While I was making the change I caught a few other typos and fixed them.

2017-02-16 17:48 UTC, freastro approved these changes

2017-02-16 17:51 UTC, merged